### PR TITLE
Add a Horreum passthrough API

### PR DESCRIPTION
**Pull request by dbutenhof**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Any Horreum `GET` API path, including query parameters, can be passed to `GET /api/v1/horreum/api/{path}`: e.g., `/api/v1/horreum/api/test?limit=10` or `/api/v1/horreum/api/test/byName/FakeTest`. The query will be authorized using the configured CPT project Horreum credentials.

The Horreum status, response body, and response headers will be returned to the caller.
## Related Tickets & Documents

Issue [PANDA-367](https://issues.redhat.com/browse/PANDA-367)

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

Deployed locally using `local-compose.sh`, along with a local populated Horreum instance, verified using `curl`. E.g.,

```
$ curl -sS http://localhost:8000/api/v1/horreum/api/test|jq
{
  "tests": [
    {
      "access": "PROTECTED",
      "owner": "dev-team",
      "id": 10,
      "name": "Fake",
      "folder": null,
      "description": "Another fake test",
      "datastoreId": 1,
      "tokens": [],
      "timelineLabels": [
        "start"
      ],
      "timelineFunction": null,
      "fingerprintLabels": [
        "job"
      ],
      "fingerprintFilter": null,
      "compareUrl": null,
      "transformers": [],
      "notificationsEnabled": true
    }
  ],
  "count": 1
}
```

### CODE REVIEW

**Review by chentex — APPROVED** [review]
LGTM. Thank you for the contribution!

**Comment by dbutenhof** [comment]
> LGTM. Thank you for the contribution!

Happy to help. Is there someone else who needs to approve this before it gets merged?

**Comment by chentex** [comment]
I've asked another set of eyes to take a look, will merge if nothing comes up

**Comment by chentex** [comment]
Hi @dbutenhof  could you rebase your PR.

**Pull request merged**
