### PR TITLE
Multi-select Filter

### PR DESCRIPTION
**Pull request by MVarshini**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR allows the user to select multiple filter values and based on selection other filter options get recalculated.

## Related Tickets & Documents

- Related Issue # [PANDA-446](https://issues.redhat.com/browse/PANDA-446)
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by chentex — CHANGES_REQUESTED** [review]
Hi @MVarshini Thank you for this it is working well, can I just ask for one more change.
Can we leave teh summary fields as a single select, that if you click one the status filters resets just to that one.

Right now if I click success, the success filter applies, and if I click failure, the failure status appends to the filter, I would like it to remove the success one and set it to failure. I don't know if it makes sense.

**Comment by MVarshini** [comment]
> Hi @MVarshini Thank you for this it is working well, can I just ask for one more change. Can we leave teh summary fields as a single select, that if you click one the status filters resets just to that one.
> 
> Right now if I click success, the success filter applies, and if I click failure, the failure status appends to the filter, I would like it to remove the success one and set it to failure. I don't know if it makes sense.

@chentex That sounds right. Updated the status filter in the Metrics tab as requested.

**Comment by vishnuchalla** [comment]
> > Hi @MVarshini Thank you for this it is working well, can I just ask for one more change. Can we leave teh summary fields as a single select, that if you click one the status filters resets just to that one.
> > Right now if I click success, the success filter applies, and if I click failure, the failure status appends to the filter, I would like it to remove the success one and set it to failure. I don't know if it makes sense.
> 
> @chentex That sounds right. Updated the status filter in the Metrics tab as requested.

Looks like along with summary fields, the same change got applied to other's as well. Was that expected?

**Comment by chentex** [comment]
Hi @vishnuchalla, I've reviewed the PR and I see it working as expected, can you explain what changes are you seeing in other fields as well?
Maybe the confusion is with my last comment where I requested the changes on the summary fields, but the multiselect should be applied to all filters.

**Review by vishnuchalla — CHANGES_REQUESTED** [review]
@MVarshini Regarding filters dropdown select, when I go select an option from the `Product` or any other option drop down filter, I have to deselect it's value to see rest of the values available otherwise I see only the current selected value as a part of dropdown. Example below.

Screenshot from 2024-07-31 13-20-56

Can you enable it with multi-select option please?

**Review by vishnuchalla — APPROVED** [review]
/lgtm

**Comment by vishnuchalla** [comment]
As per our discussion offline, my filters concern got addressed. Thanks @MVarshini

**Pull request merged**
