### PR TITLE
fixing endpoints nomenclature

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Following standard naming convention for Fast API endpoints.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Tested in local using `sh local-compose.sh`.

### CODE REVIEW

**Review by athiruma — APPROVED** [review]
/lgmt

**Review by jtaleric — COMMENTED** [review]
lgtm, need to test locally before i blindly approve :)

**Review by jtaleric — APPROVED** [review]
tested, lgtm!

**Review by chentex — APPROVED** [review]
/lgtm

**Pull request merged**
